- name: Build a TinyIPA image
  command: make
  args:
    chdir: '{{ tinyipa_dir }}'
  environment:
    BRANCH_PATH: '{{ ipa_branch_path }}'
    IPA_SOURCE_DIR: '{{ ansible_user_dir }}/src/opendev.org/openstack/ironic-python-agent'

- name: Build a TinyIPA iso
  command: make iso
  args:
    chdir: '{{ tinyipa_dir }}'
  environment:
    BRANCH_PATH: '{{ ipa_branch_path }}'
    IPA_SOURCE_DIR: '{{ ansible_user_dir }}/src/opendev.org/openstack/ironic-python-agent'
  when: "'ussuri' not in ipa_branch_path"

- name: Move resulting files
  shell: |
    mv tinyipa*.tar.gz* "{{ ipa_tar_dir }}"
    mv tinyipa*.* "{{ ipa_raw_dir }}"
    mv tiny-instance-uec*.tar.gz "{{ ipa_tar_dir }}"
  args:
    chdir: '{{ tinyipa_dir }}'

# NOTE(sambetts) Must clean up chroot directories before
# publisher rsync command tries and fails to read them
- name: Clean up the environment
  command: make clean
  args:
    chdir: '{{ tinyipa_dir }}'
