- project:
    templates:
      - publish-openstack-docs-pti
      - check-requirements
      - release-notes-jobs-python3
    check:
      jobs:
        - openstack-tox-pep8
        - ironic-standalone-ipa-src
        - ipa-tempest-bios-ipmi-direct-tinyipa-src
        - ipa-tempest-bios-ipmi-iscsi-tinyipa-src
        - ironic-python-agent-check-image-tinyipa
        - ironic-python-agent-check-image-dib-centos8
        - ironic-python-agent-check-image-dib-centos8-extra
        - ironic-python-agent-check-image-dib-centos7
        - ironic-python-agent-check-image-dib-debian
        - ironic-python-agent-check-image-dib-debian-extra
        # Non-voting jobs
        - ironic-python-agent-check-image-dib-centos7-python3:
            voting: false
        - ironic-python-agent-check-image-dib-fedora:
            voting: false
        - ironic-python-agent-check-image-dib-ubuntu:
            voting: false
        - ironic-python-agent-check-image-dib-opensuse:
            voting: false
        - ipa-tempest-wholedisk-bios-ipmi-direct-dib-src:
            voting: false
        - ipa-tempest-bios-ipmi-iscsi-src:
            voting: false
        - ipa-tempest-ironic-inspector-src:
            voting: false
        - tripleo-buildimage-ironic-python-agent-centos-8:
            voting: false
        - ironic-python-agent-test-image-tinyipa-ussuri:
            voting: false
    gate:
      jobs:
        - openstack-tox-pep8
        - ironic-standalone-ipa-src
        - ipa-tempest-bios-ipmi-direct-tinyipa-src
        - ipa-tempest-bios-ipmi-iscsi-tinyipa-src
        - ironic-python-agent-check-image-tinyipa
        - ironic-python-agent-check-image-dib-centos8
        - ironic-python-agent-check-image-dib-centos8-extra
        - ironic-python-agent-check-image-dib-centos7
        - ironic-python-agent-check-image-dib-debian
        - ironic-python-agent-check-image-dib-debian-extra
    post:
      jobs:
        - publish-openstack-python-branch-tarball
        - ironic-python-agent-build-image-tinyipa
        - ironic-python-agent-build-image-dib-centos8
        - ironic-python-agent-build-image-dib-debian
