on:
  push:
    branches: [master]
  pull_request:
    branches: [master]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        release: [ussuri, victoria]
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v2
      - run: sudo apt-get update
      - run: sudo apt-get install kpartx qemu-utils
      - run: pip install .
      - run: ironic-python-agent-builder centos
        env:
          DIB_DHCP_TIMEOUT: 60
          DIB_REPOLOCATION_ironic_python_agent: https://github.com/vexxhost/ironic-python-agent
          DIB_REPOREF_ironic_python_agent: stable/${{ matrix.release }}
      - uses: actions/upload-artifact@v2
        with:
          name: ironic-python-agent-${{ matrix.release }}
          path: ironic-python-agent*
          if-no-files-found: error
